### ISSUE TITLE
Inaccurate installation guide

### ISSUE THREAD

**Issue by abhash-rai** [sachadee/Dlib#2]
for python 3.8
It shouldn't be: python -m pip install dlib-19.22.99-cp38-cp38m-win_amd64.whl
It should be: python -m pip install dlib-19.22.99-cp38-cp38-win_amd64.whl

python 3.9
It shouldn't be: python -m pip install dlib-19.22.99-cp39-cp39m-win_amd64.whl
It should be: python -m pip install dlib-19.22.99-cp39-cp39-win_amd64.whl

**Comment by r-a-j-a-n** [comment]
No , it's correct 
The file name have cp38m so it must be python -m pip install dlib-19.22.99-cp38-cp38m-win_amd64.whl only

**Comment by sachadee** [comment]
Corrected Thanks!!!
